# test:
#   stage: test
#   script:
#     - cd blog4
#     - bundle install
#     - rails db:migrate RAILS_ENV=test
#     - rails test
#   only:
#     - blog4

deploy:
  stage: deploy
  script:
    - pumactl stop -P tmp/pids/server.pid || true
    - rsync -arv --delete ./blog4 ~
    - cd ~/blog4
    - bundle install
    - rails g devise:install
    - rails db:migrate
    - nohup rails server -d -b 0.0.0.0 -p 4000 &
    - echo success
  only:
    - blog4
