deploy:
  stage: deploy
  script:
    - sudo apt-get install -y rsync
    - rsync -arv --delete ./cookbook3 ~
    - cd ~/cookbook3
    - bundle install
    - rails db:migrate
    - nohup rails server -d -b 0.0.0.0 -p 3000 &
  only:
      - cookbook3 
