test:
  stage: test
  script:
    - cd cookbook3
    - bundle install
    - rails db:migrate RAILS_ENV=test
    - rails test
  only:
    - cookbook3

deploy:
  stage: deploy
  script:
    - sudo apt-get install -y rsync
    - rsync -arv --delete ./cookbook3 ~
    - cd ~/cookbook3
    - gem install bundler:2.2.29
    - bundle install
    - rake assets:precompile 
    - rails db:migrate
    - nohup rails server -d -b 0.0.0.0 -p 3000 &
  only:
    - cookbook3 
