deploy:
  stage: deploy
  script:
    - sudo apt-get install -y rsync
    - rsync -arv --delete ./cookbook3 ~
    - cd ~/cookbook3
    - gem install bundler:2.2.29
    - bundle install
    - rails db:migrate
    - rake assets:precompile
    - nohup rails server -d -b 115.25.139.10 -p 13395 &
  only:
    - cookbook3 
